### ISSUE TITLE
files in diffusion_edf/demo  which supposed to be train data are actually empty file 

### ISSUE THREAD

**Issue by wanboyan** [tomato1mule/diffusion_edf#1]

**Comment by tomato1mule** [comment]
Thank you for your interest in our project. 
I'd like to confirm that the files are indeed present in the `demo` directory.

For example, you can find the files such as colors.pt, points.pt, and metadata.yaml in the following directory: `demo/sapien_demo_5_mug_20230727/data/demo_0/step_0/scene_pcd`.
(link: [https://github.com/tomato1mule/diffusion_edf/tree/main/demo/sapien_demo_5_mug_20230727/data/demo_0/step_0/scene_pcd](url))

However, it is possible that the folders appear to be empty due to Github LFS (large file storage) related issues.
Please let me know if the issue persists.

Thank you!
